apiVersion: 1

datasources:
  - name: RFID Operations Prometheus
    uid: prometheus-rfid-ops
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
